//! Task streaming module for real-time event delivery.
//!
//! This module provides types and utilities for streaming ephemeral events
//! from tasks to connected clients in real-time. Stream events are not
//! persisted and are delivered via Server-Sent Events (SSE).
//!
//! # Use Cases
//!
//! - **LLM Token Streaming**: Stream tokens as they're generated by language models
//! - **Progress Visibility**: Real-time progress updates for long-running tasks
//! - **Data Pipelines**: Stream intermediate results during data processing
//! - **Error Notification**: Immediate error feedback to monitoring systems
//!
//! # Example
//!
//! ```rust,ignore
//! use flovyn_sdk::task::streaming::StreamEvent;
//!
//! async fn my_task(ctx: &impl TaskContext) -> Result<Output> {
//!     // Stream tokens as they're generated
//!     for token in llm.stream_completion(prompt).await? {
//!         ctx.stream_token(&token).await?;
//!     }
//!
//!     // Stream progress
//!     ctx.stream_progress(0.5, Some("Halfway done")).await?;
//!
//!     // Stream custom data
//!     ctx.stream_data(json!({"processed": 100})).await?;
//!
//!     Ok(output)
//! }
//! ```
//!
//! # Semantics
//!
//! - Events are **ephemeral** (not persisted)
//! - Delivery is **best-effort** (fire-and-forget)
//! - No event replay (live only)
//! - Streaming errors don't fail the task

// Re-export streaming types from core
pub use flovyn_core::task::streaming::{
    StreamError, StreamEvent, StreamEventType, TaskStreamEvent,
};
