//! Task streaming module for real-time event delivery.
//!
//! This module provides types and utilities for streaming ephemeral events
//! from tasks to connected clients in real-time. Stream events are not
//! persisted and are delivered via Server-Sent Events (SSE).
//!
//! # Use Cases
//!
//! - **LLM Token Streaming**: Stream tokens as they're generated by language models
//! - **Progress Visibility**: Real-time progress updates for long-running tasks
//! - **Data Pipelines**: Stream intermediate results during data processing
//! - **Error Notification**: Immediate error feedback to monitoring systems

mod types;

pub use types::{StreamError, StreamEvent, StreamEventType, TaskStreamEvent};
