//! # Flovyn FFI
//!
//! This crate provides uniffi bindings for the Flovyn workflow orchestration platform,
//! enabling cross-language SDK support for Kotlin, Swift, and Python.
//!
//! ## Architecture
//!
//! The FFI layer exposes an activation-based protocol where:
//! - Core polls for work and returns `WorkflowActivation` / `TaskActivation`
//! - Language SDK processes activations and returns completions
//! - Core handles all gRPC communication, replay, and determinism validation
//!
//! ## Exported Types
//!
//! ### Objects (classes with methods)
//! - [`CoreWorker`] - Main worker object with poll/complete methods
//! - [`CoreClient`] - Client for starting workflows, queries, signals
//!
//! ### Records (data classes)
//! - [`WorkflowActivation`] - Workflow work to process
//! - [`TaskActivation`] - Task work to process
//! - [`WorkerConfig`] - Worker configuration
//! - [`ClientConfig`] - Client configuration
//!
//! ### Enums
//! - [`FfiWorkflowCommand`] - Commands generated by workflow execution
//! - [`WorkflowActivationJob`] - Jobs within an activation
//! - [`WorkflowCompletionStatus`] - Workflow completion result
//! - [`TaskCompletion`] - Task completion result
//! - [`FfiError`] - Error types
//!
//! ## Usage
//!
//! ```ignore
//! // In Kotlin (pseudo-code)
//! val worker = CoreWorker.new(config)
//! while (true) {
//!     val activation = worker.pollWorkflowActivation()
//!     // Process activation, generate commands
//!     val commands = listOf(...)
//!     val status = WorkflowCompletionStatus.Completed(output)
//!     worker.completeWorkflowActivation(activation.runId, commands, status)
//! }
//! ```

mod activation;
mod client;
mod command;
mod config;
mod context;
mod error;
mod types;
mod worker;

// Re-export all FFI types
pub use activation::*;
pub use client::*;
pub use command::*;
pub use config::*;
pub use context::*;
pub use error::*;
pub use types::*;
pub use worker::*;

// Generate uniffi scaffolding
uniffi::setup_scaffolding!();
