//! Workflow commands generated during execution

use serde::{Deserialize, Serialize};
use serde_json::Value;
use uuid::Uuid;

/// Commands generated by workflow execution that will be persisted as events
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(tag = "type")]
pub enum WorkflowCommand {
    /// Record the result of a ctx.run() operation
    RecordOperation {
        sequence_number: i32,
        #[serde(rename = "operationName")]
        operation_name: String,
        result: Value,
    },

    /// Set workflow state
    SetState {
        sequence_number: i32,
        key: String,
        value: Value,
    },

    /// Clear a specific state key
    ClearState { sequence_number: i32, key: String },

    /// Schedule a task for execution
    ScheduleTask {
        sequence_number: i32,
        #[serde(rename = "taskType")]
        task_type: String,
        #[serde(rename = "taskExecutionId")]
        task_execution_id: Uuid,
        input: Value,
        #[serde(rename = "prioritySeconds", skip_serializing_if = "Option::is_none")]
        priority_seconds: Option<i32>,
        #[serde(rename = "maxRetries", skip_serializing_if = "Option::is_none")]
        max_retries: Option<u32>,
        #[serde(rename = "timeoutMs", skip_serializing_if = "Option::is_none")]
        timeout_ms: Option<i64>,
        #[serde(skip_serializing_if = "Option::is_none")]
        queue: Option<String>,
    },

    /// Schedule a child workflow
    ScheduleChildWorkflow {
        sequence_number: i32,
        name: String,
        #[serde(skip_serializing_if = "Option::is_none")]
        kind: Option<String>,
        #[serde(rename = "definitionId", skip_serializing_if = "Option::is_none")]
        definition_id: Option<Uuid>,
        #[serde(rename = "childExecutionId")]
        child_execution_id: Uuid,
        input: Value,
        #[serde(rename = "taskQueue")]
        task_queue: String,
        #[serde(rename = "prioritySeconds")]
        priority_seconds: i32,
    },

    /// Complete the workflow successfully
    CompleteWorkflow { sequence_number: i32, output: Value },

    /// Fail the workflow with an error
    FailWorkflow {
        sequence_number: i32,
        error: String,
        #[serde(rename = "stackTrace")]
        stack_trace: String,
        #[serde(rename = "failureType", skip_serializing_if = "Option::is_none")]
        failure_type: Option<String>,
    },

    /// Suspend the workflow (waiting for external event)
    SuspendWorkflow {
        sequence_number: i32,
        reason: String,
    },

    /// Cancel the workflow
    CancelWorkflow {
        sequence_number: i32,
        reason: String,
    },

    /// Create a durable promise
    CreatePromise {
        sequence_number: i32,
        #[serde(rename = "promiseId")]
        promise_id: String,
        #[serde(rename = "timeoutMs", skip_serializing_if = "Option::is_none")]
        timeout_ms: Option<i64>,
    },

    /// Resolve a durable promise
    ResolvePromise {
        sequence_number: i32,
        #[serde(rename = "promiseId")]
        promise_id: String,
        value: Value,
    },

    /// Start a timer
    StartTimer {
        sequence_number: i32,
        #[serde(rename = "timerId")]
        timer_id: String,
        #[serde(rename = "durationMs")]
        duration_ms: i64,
    },

    /// Cancel a timer
    CancelTimer {
        sequence_number: i32,
        #[serde(rename = "timerId")]
        timer_id: String,
    },

    /// Request cancellation of a scheduled task
    RequestCancelTask {
        sequence_number: i32,
        #[serde(rename = "taskExecutionId")]
        task_execution_id: Uuid,
    },

    /// Request cancellation of a child workflow
    RequestCancelChildWorkflow {
        sequence_number: i32,
        #[serde(rename = "childExecutionId")]
        child_execution_id: Uuid,
    },
}

impl WorkflowCommand {
    /// Get the sequence number of this command
    pub fn sequence_number(&self) -> i32 {
        match self {
            Self::RecordOperation {
                sequence_number, ..
            } => *sequence_number,
            Self::SetState {
                sequence_number, ..
            } => *sequence_number,
            Self::ClearState {
                sequence_number, ..
            } => *sequence_number,
            Self::ScheduleTask {
                sequence_number, ..
            } => *sequence_number,
            Self::ScheduleChildWorkflow {
                sequence_number, ..
            } => *sequence_number,
            Self::CompleteWorkflow {
                sequence_number, ..
            } => *sequence_number,
            Self::FailWorkflow {
                sequence_number, ..
            } => *sequence_number,
            Self::SuspendWorkflow {
                sequence_number, ..
            } => *sequence_number,
            Self::CancelWorkflow {
                sequence_number, ..
            } => *sequence_number,
            Self::CreatePromise {
                sequence_number, ..
            } => *sequence_number,
            Self::ResolvePromise {
                sequence_number, ..
            } => *sequence_number,
            Self::StartTimer {
                sequence_number, ..
            } => *sequence_number,
            Self::CancelTimer {
                sequence_number, ..
            } => *sequence_number,
            Self::RequestCancelTask {
                sequence_number, ..
            } => *sequence_number,
            Self::RequestCancelChildWorkflow {
                sequence_number, ..
            } => *sequence_number,
        }
    }

    /// Set the sequence number of this command
    pub fn set_sequence_number(&mut self, seq: i32) {
        match self {
            Self::RecordOperation {
                sequence_number, ..
            } => *sequence_number = seq,
            Self::SetState {
                sequence_number, ..
            } => *sequence_number = seq,
            Self::ClearState {
                sequence_number, ..
            } => *sequence_number = seq,
            Self::ScheduleTask {
                sequence_number, ..
            } => *sequence_number = seq,
            Self::ScheduleChildWorkflow {
                sequence_number, ..
            } => *sequence_number = seq,
            Self::CompleteWorkflow {
                sequence_number, ..
            } => *sequence_number = seq,
            Self::FailWorkflow {
                sequence_number, ..
            } => *sequence_number = seq,
            Self::SuspendWorkflow {
                sequence_number, ..
            } => *sequence_number = seq,
            Self::CancelWorkflow {
                sequence_number, ..
            } => *sequence_number = seq,
            Self::CreatePromise {
                sequence_number, ..
            } => *sequence_number = seq,
            Self::ResolvePromise {
                sequence_number, ..
            } => *sequence_number = seq,
            Self::StartTimer {
                sequence_number, ..
            } => *sequence_number = seq,
            Self::CancelTimer {
                sequence_number, ..
            } => *sequence_number = seq,
            Self::RequestCancelTask {
                sequence_number, ..
            } => *sequence_number = seq,
            Self::RequestCancelChildWorkflow {
                sequence_number, ..
            } => *sequence_number = seq,
        }
    }

    /// Get the type name of this command (for logging/debugging)
    pub fn type_name(&self) -> &'static str {
        match self {
            Self::RecordOperation { .. } => "RecordOperation",
            Self::SetState { .. } => "SetState",
            Self::ClearState { .. } => "ClearState",
            Self::ScheduleTask { .. } => "ScheduleTask",
            Self::ScheduleChildWorkflow { .. } => "ScheduleChildWorkflow",
            Self::CompleteWorkflow { .. } => "CompleteWorkflow",
            Self::FailWorkflow { .. } => "FailWorkflow",
            Self::SuspendWorkflow { .. } => "SuspendWorkflow",
            Self::CancelWorkflow { .. } => "CancelWorkflow",
            Self::CreatePromise { .. } => "CreatePromise",
            Self::ResolvePromise { .. } => "ResolvePromise",
            Self::StartTimer { .. } => "StartTimer",
            Self::CancelTimer { .. } => "CancelTimer",
            Self::RequestCancelTask { .. } => "RequestCancelTask",
            Self::RequestCancelChildWorkflow { .. } => "RequestCancelChildWorkflow",
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn test_sequence_number() {
        let cmd = WorkflowCommand::RecordOperation {
            sequence_number: 5,
            operation_name: "test".to_string(),
            result: json!(42),
        };
        assert_eq!(cmd.sequence_number(), 5);
    }

    #[test]
    fn test_set_sequence_number() {
        let mut cmd = WorkflowCommand::RecordOperation {
            sequence_number: 1,
            operation_name: "test".to_string(),
            result: json!(42),
        };
        cmd.set_sequence_number(10);
        assert_eq!(cmd.sequence_number(), 10);
    }

    #[test]
    fn test_type_name() {
        let cmd = WorkflowCommand::RecordOperation {
            sequence_number: 1,
            operation_name: "test".to_string(),
            result: json!(42),
        };
        assert_eq!(cmd.type_name(), "RecordOperation");

        let cmd = WorkflowCommand::ScheduleTask {
            sequence_number: 1,
            task_type: "my-task".to_string(),
            task_execution_id: Uuid::new_v4(),
            input: json!({}),
            priority_seconds: None,
            max_retries: None,
            timeout_ms: None,
            queue: None,
        };
        assert_eq!(cmd.type_name(), "ScheduleTask");
    }

    #[test]
    fn test_serialize_record_operation() {
        let cmd = WorkflowCommand::RecordOperation {
            sequence_number: 1,
            operation_name: "fetch-user".to_string(),
            result: json!({"id": 123, "name": "Alice"}),
        };

        let json = serde_json::to_string(&cmd).unwrap();
        assert!(json.contains("RecordOperation"));
        assert!(json.contains("fetch-user"));
        assert!(json.contains("operationName"));

        let parsed: WorkflowCommand = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, cmd);
    }

    #[test]
    fn test_serialize_schedule_task() {
        let task_id = Uuid::new_v4();
        let cmd = WorkflowCommand::ScheduleTask {
            sequence_number: 2,
            task_type: "payment-task".to_string(),
            task_execution_id: task_id,
            input: json!({"amount": 100}),
            priority_seconds: Some(60),
            max_retries: Some(3),
            timeout_ms: Some(30000),
            queue: Some("high-priority".to_string()),
        };

        let json = serde_json::to_string(&cmd).unwrap();
        assert!(json.contains("ScheduleTask"));
        assert!(json.contains("payment-task"));
        assert!(json.contains("taskType"));
        assert!(json.contains("prioritySeconds"));
        assert!(json.contains("maxRetries"));
        assert!(json.contains("timeoutMs"));
        assert!(json.contains("high-priority"));

        let parsed: WorkflowCommand = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, cmd);
    }

    #[test]
    fn test_serialize_complete_workflow() {
        let cmd = WorkflowCommand::CompleteWorkflow {
            sequence_number: 10,
            output: json!({"status": "success", "result": 42}),
        };

        let json = serde_json::to_string(&cmd).unwrap();
        let parsed: WorkflowCommand = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, cmd);
    }

    #[test]
    fn test_serialize_fail_workflow() {
        let cmd = WorkflowCommand::FailWorkflow {
            sequence_number: 5,
            error: "Something went wrong".to_string(),
            stack_trace: "at main.rs:10".to_string(),
            failure_type: Some("PERMANENT".to_string()),
        };

        let json = serde_json::to_string(&cmd).unwrap();
        assert!(json.contains("failureType"));
        assert!(json.contains("stackTrace"));

        let parsed: WorkflowCommand = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, cmd);
    }

    #[test]
    fn test_serialize_child_workflow() {
        let cmd = WorkflowCommand::ScheduleChildWorkflow {
            sequence_number: 3,
            name: "process-payment".to_string(),
            kind: Some("payment-workflow".to_string()),
            definition_id: None,
            child_execution_id: Uuid::new_v4(),
            input: json!({"orderId": "123"}),
            task_queue: "default".to_string(),
            priority_seconds: 0,
        };

        let json = serde_json::to_string(&cmd).unwrap();
        assert!(json.contains("childExecutionId"));
        assert!(json.contains("taskQueue"));

        let parsed: WorkflowCommand = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, cmd);
    }

    #[test]
    fn test_serialize_timer() {
        let cmd = WorkflowCommand::StartTimer {
            sequence_number: 4,
            timer_id: "timer-1".to_string(),
            duration_ms: 5000,
        };

        let json = serde_json::to_string(&cmd).unwrap();
        assert!(json.contains("timerId"));
        assert!(json.contains("durationMs"));

        let parsed: WorkflowCommand = serde_json::from_str(&json).unwrap();
        assert_eq!(parsed, cmd);
    }

    #[test]
    fn test_all_command_types_have_sequence_number() {
        let commands = vec![
            WorkflowCommand::RecordOperation {
                sequence_number: 1,
                operation_name: "op".to_string(),
                result: json!(null),
            },
            WorkflowCommand::SetState {
                sequence_number: 2,
                key: "k".to_string(),
                value: json!(null),
            },
            WorkflowCommand::ClearState {
                sequence_number: 3,
                key: "k".to_string(),
            },
            WorkflowCommand::ScheduleTask {
                sequence_number: 4,
                task_type: "t".to_string(),
                task_execution_id: Uuid::nil(),
                input: json!(null),
                priority_seconds: None,
                max_retries: None,
                timeout_ms: None,
                queue: None,
            },
            WorkflowCommand::ScheduleChildWorkflow {
                sequence_number: 5,
                name: "n".to_string(),
                kind: None,
                definition_id: None,
                child_execution_id: Uuid::nil(),
                input: json!(null),
                task_queue: "q".to_string(),
                priority_seconds: 0,
            },
            WorkflowCommand::CompleteWorkflow {
                sequence_number: 6,
                output: json!(null),
            },
            WorkflowCommand::FailWorkflow {
                sequence_number: 7,
                error: "e".to_string(),
                stack_trace: "s".to_string(),
                failure_type: None,
            },
            WorkflowCommand::SuspendWorkflow {
                sequence_number: 8,
                reason: "r".to_string(),
            },
            WorkflowCommand::CancelWorkflow {
                sequence_number: 9,
                reason: "r".to_string(),
            },
            WorkflowCommand::CreatePromise {
                sequence_number: 10,
                promise_id: "p".to_string(),
                timeout_ms: None,
            },
            WorkflowCommand::ResolvePromise {
                sequence_number: 11,
                promise_id: "p".to_string(),
                value: json!(null),
            },
            WorkflowCommand::StartTimer {
                sequence_number: 12,
                timer_id: "t".to_string(),
                duration_ms: 1000,
            },
            WorkflowCommand::CancelTimer {
                sequence_number: 13,
                timer_id: "t".to_string(),
            },
            WorkflowCommand::RequestCancelTask {
                sequence_number: 14,
                task_execution_id: Uuid::nil(),
            },
            WorkflowCommand::RequestCancelChildWorkflow {
                sequence_number: 15,
                child_execution_id: Uuid::nil(),
            },
        ];

        for (i, cmd) in commands.iter().enumerate() {
            assert_eq!(cmd.sequence_number(), (i + 1) as i32);
        }
    }
}
